services:
  selenium-hub:
    image: selenium/hub:4.28.1
    container_name: selenium-hub
    ports:
      - "4444:4444"

  chrome-node:
    image: selenium/node-chromium:4.28.1
    shm_size: 2gb
    container_name: chrome-node
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  firefox-node:
    image: selenium/node-firefox:4.28.1
    shm_size: 2gb
    container_name: firefox-node
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  tests:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./.env.${TEST_ENV:-test}:/app/.env.${TEST_ENV:-test}
    env_file:
      - ./.env.${TEST_ENV:-test}
    container_name: test-runner
    depends_on:
      - selenium-hub
      - chrome-node
      - firefox-node
    environment:
      - TEST_TAGS=${TEST_TAGS:-}
      - TEST_ENV=${TEST_ENV:-test}
    command: /bin/sh -c 'mvn test -Dcucumber.filter.tags="'"$${TEST_TAGS}"'"'